# Generated by Django 5.2.7 on 2025-10-30 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('stock_description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Ultima atualização')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id_supplier', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Doador')),
                ('supplier_type', models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('PF', 'Pessoa Física')], max_length=2, verbose_name='Tipo de doador')),
                ('tax_id', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('zip_code', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rua')),
                ('address_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('address_complement', models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('is_anonymous', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id_stockentry', models.AutoField(primary_key=True, serialize=False)),
                ('batch', models.IntegerField(verbose_name='Lote')),
                ('entry_date', models.DateField(auto_now_add=True, verbose_name='Data da Entrada')),
                ('entry_time', models.TimeField(auto_now_add=True, verbose_name='Hora da Entrada')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('exit_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Saída')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponibilidade')),
                ('stock_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='stock.stock', verbose_name='Estoque')),
                ('supplier_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.supplier', verbose_name='Fornecedor')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='suppliers',
            field=models.ManyToManyField(through='stock.StockEntry', to='stock.supplier'),
        ),
    ]
