# Generated by Django 5.2.7 on 2025-10-30 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50, verbose_name='Nome Projeto')),
                ('project_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data do fim')),
                ('project_type', models.CharField(choices=[('course', 'Curso'), ('Meeting', 'Encontro'), ('Lecture', 'Palestra')], max_length=20, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id_Enrollment', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_stamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Inscrição')),
                ('beneficiary_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaries.beneficiary', verbose_name='Beneficiário')),
                ('project_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Projeto')),
            ],
            options={
                'unique_together': {('beneficiary_fk', 'project_fk')},
            },
        ),
    ]
