# Generated by Django 5.2.7 on 2025-10-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id_beneficiary', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiary_name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('zip_code', models.CharField(max_length=9, verbose_name='CEP')),
                ('street', models.CharField(max_length=200, verbose_name='Rua')),
                ('address_number', models.CharField(max_length=10, verbose_name='Número')),
                ('address_complement', models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('occupation', models.CharField(max_length=100, verbose_name='Profissão')),
                ('family_income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Renda Familiar')),
                ('dependents_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Nº dependentes')),
                ('household_members', models.IntegerField(verbose_name='Nº de pessoas da Família')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('pending', 'Pendente'), ('suspended', 'Suspenso')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Ultima atualização')),
            ],
        ),
    ]
