# Generated by Django 5.2.7 on 2025-10-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='projects',
            field=models.ManyToManyField(through='projects.Enrollment', to='projects.project'),
        ),
    ]
