# Generated by Django 5.2.7 on 2025-11-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'verbose_name': 'Beneficiário', 'verbose_name_plural': 'Beneficiários'},
        ),
    ]
