# Generated by Django 5.2.7 on 2025-11-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0003_alter_beneficiary_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='address_number',
            field=models.IntegerField(verbose_name='Número'),
        ),
    ]
