# Generated by Django 5.2.7 on 2025-10-30 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id_donation', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('donation_date', models.DateField(auto_now_add=True, verbose_name='Data da Doação')),
                ('donation_time', models.TimeField(auto_now_add=True, verbose_name='Hora da Doação')),
                ('donation_month', models.IntegerField(verbose_name='Mês da Doação')),
                ('donation_year', models.IntegerField(verbose_name='Ano da Doação')),
                ('beneficiary_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaries.beneficiary', verbose_name='Beneficiário')),
                ('stock_entry_fk', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='stock.stockentry', verbose_name='Entrada de Estoque')),
            ],
            options={
                'unique_together': {('beneficiary_fk', 'donation_month', 'donation_year')},
            },
        ),
    ]
