# Generated by Django 5.2.7 on 2025-11-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Doação', 'verbose_name_plural': 'Doações'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
    ]
