# Generated by Django 5.2.7 on 2025-11-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donation_options_alter_donation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_month',
            field=models.CharField(choices=[('1', 'Janeiro'), ('2', 'Fevereiro'), ('3', 'Março'), ('4', 'Abril'), ('5', 'Maio'), ('6', 'Junho'), ('7', 'Julho'), ('8', 'Agosto'), ('9', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=2, verbose_name='Mês da Doação'),
        ),
    ]
